name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: true

      - name: Install dependencies
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_cran("rsconnect")'
          R -e 'remotes::install_cran(c("shiny", "ggplot2", "colorRamps", "dplyr", "tidyr", "ggh4x"))'

      - name: Verify Installed Packages
        run: |
          R -e 'print(installed.packages()[,1])'

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: "environmentalwebapplication"
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          R -e 'if (!requireNamespace("rsconnect", quietly=TRUE)) install.packages("rsconnect")'
          R -e 'library(rsconnect);
                rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_NAME"), 
                                          token=Sys.getenv("SHINYAPPS_TOKEN"), 
                                          secret=Sys.getenv("SHINYAPPS_SECRET"))'
          R -e 'rsconnect::deployApp()'
